class order {
  final double orderId;
  final String orderRefNum;
  final String headOfAllocation;
  final String Manufacturer;
  var orderDate;
  final String orderDescription;
  final double financialYear;
  final String productionUnit;

  order(
      {required this.orderId,
      required this.orderRefNum,
      required this.headOfAllocation,
      required this.Manufacturer,
      this.orderDate,
      required this.orderDescription,
      required this.financialYear,
      required this.productionUnit});

  static List<order> getOrders() {
    return [
      order(
          orderId: 1000,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR SDGFJHNGJGHNSKSDNFK",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1001,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1002,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1003,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1004,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1005,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1006,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1007,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1008,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1009,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1000,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR bdwhdbd",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1001,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1002,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-adbskjdfh",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1003,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1004,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1005,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1006,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1007,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1008,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
      order(
          orderId: 1009,
          orderRefNum: "RFS2019",
          headOfAllocation: "",
          Manufacturer: "DMW",
          orderDate: "23/5/2022",
          orderDescription: "M231-WR",
          financialYear: 2022 - 23,
          productionUnit: ""),
    ];
  }
}